version: '3.8'

services:
  api:
    build:
      context: ./app  # Utiliser le dossier monitoring comme contexte
    ports:
      - "8000:8000"  # API accessible sur localhost:8000
    volumes:
      - ./app:/app  # Monte le code local dans le conteneur

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Interface web de Prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring



