global:
  scrape_interval: 15s  # Intervalle pour collecter les métriques
scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]  # Correct ! Utilise le port interne

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']